# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InstaClone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModel',
        ),
    ]
