# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaClone', '0002_remove_postmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
