# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstaClone', '0003_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.FileField(upload_to='user_images'),
        ),
    ]
